# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Epa ICR Intranet
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-datapage-generator

contentful:
  spaces:
    - epa-icr-intranet:                    # Jekyll _data folder identifier - Required
        space: ENV_CONTENTFUL_SPACE_ID  # Required - should be moved to secret area
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN # Required - should be moved to secret area
        destination: contentful

# Generate blog pages example
page_gen-dirs: false

page_gen:
- data: 'site.data.contentful.epa-icr-intranet.basic'
  template: 'basic'
  dir: "basic"
  name: 'url_path'